version: "3.1"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=A!MDevel0p#
      - MSSQL_PID=Developer
    volumes:
      - mssqldata:/var/opt/mssql